###############################################################################
# Brownthrower configuration template                                         #
#                                                                             #
# Each setting has a comment above explaining its function.                   #
# Uncomment any setting you want to override and provide a suitable value.    #
###############################################################################

### Database connection settings
# database_url : sqlite:///

### Max number of history lines to be preserved. -1 for no limit.si
# history_length : 1000