###############################################################################
# Brownthrower configuration template                                         #
#                                                                             #
# Each setting has a comment above explaining its function.                   #
# Uncomment any setting you want to override and provide a suitable value.    #
###############################################################################

### Database connection settings
#database_url : sqlite:///

### Max number of history lines to be preserved. -1 for no limit.si
#history_length : 1000

### Logging configuration
#logging : 
#    version : 1
#    loggers :
#        '' :
#            level : NOTSET
#            handlers :
#                - console
#    handlers :
#        console :
#            class : logging.StreamHandler
#            level : INFO
#            formatter : standard
#            stream : ext://sys.stdout
#    formatters :
#        standard :
#            format : '%(asctime)s %(name)s %(module)s line:%(lineno)d %(levelname)s %(message)s'
