###############################################################################
# Brownthrower configuration template                                         #
#                                                                             #
# Each setting has a comment above explaining its function.                   #
# Uncomment any setting you want to override and provide a suitable value.    #
###############################################################################

### Database connection settings
database_url : sqlite:///

### Command to launch a text editting application
editor: nano

### Pager for displaying large chunks of text
pager: less

### Max number of history lines to be preserved. -1 for no limit.
history_length : 1000

### Logging configuration
logging : 
    version : 1
    loggers :
        '' :
            level : WARNING
            handlers :
                - console
    handlers :
        console :
            class : logging.StreamHandler
            formatter : detailed
            stream : ext://sys.stderr
    formatters :
        detailed :
            format : '%(asctime)s %(name)s %(module)s line:%(lineno)d %(levelname)s %(message)s'
